TodoApplication2/Controllers/Todos1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TodoApplication2.Data;
using TodoApplication2.Models;

namespace TodoApplication2.Controllers
{
    public class Todos1Controller : Controller
    {
        private readonly TodoApplicationContext _context;

        public Todos1Controller(TodoApplicationContext context)
        {
            _context = context;
        }

        // GET: Todos1
        public async Task<IActionResult> Index(string todoType, string searchString)
        {
            // Use LINQ to get list of genres
            IQueryable<string> typeQuery = from t in _context.Todo
                                           orderby t.Type
                                           select t.Type;

            var todos = from t in _context.Todo
                        select t;

            if (!string.IsNullOrEmpty(searchString))
            {
                todos = todos.Where(t => t.Title.Contains(searchString));
            }
            if (!string.IsNullOrEmpty(todoType))
            {
                todos = todos.Where(t => t.Type == todoType);
            }
            var todoTypeVM = new TodoViewModel
            {
                Types = new SelectList(await typeQuery.Distinct().ToListAsync()),
                Todos = await todos.ToListAsync()
            };
            return View(todoTypeVM);
        }

        // GET: Todos1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var todo = await _context.Todo
                .FirstOrDefaultAsync(m => m.ID == id);
            if (todo == null)
            {
                return NotFound();
            }

            return View(todo);
        }

        // GET: Todos1/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Todos1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,Type,DoneByDate,IsCompleted,Difficulty")] Todo todo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(todo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(todo);
        }

        // GET: Todos1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var todo = await _context.Todo.FindAsync(id);
            if (todo == null)
            {
                return NotFound();
            }
            return View(todo);
        }

        // POST: Todos1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,Type,DoneByDate,IsCompleted,Difficulty")] Todo todo)
        {
            if (id != todo.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(todo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TodoExists(todo.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(todo);
        }

        // GET: Todos1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var todo = await _context.Todo
                .FirstOrDefaultAsync(m => m.ID == id);
            if (todo == null)
            {
                return NotFound();
            }

            return View(todo);
        }

        // POST: Todos1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var todo = await _context.Todo.FindAsync(id);
            _context.Todo.Remove(todo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TodoExists(int id)
        {
            return _context.Todo.Any(e => e.ID == id);
        }
    }
}

TodoApplication2/Views/Todos1/Create.cshtml
@model TodoApplication2.Models.Todo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Todo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoneByDate" class="control-label"></label>
                <input asp-for="DoneByDate" class="form-control" />
                <span asp-validation-for="DoneByDate" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <label asp-for="Difficulty" class="control-label"></label>
                <input asp-for="Difficulty" class="form-control" />
                <span asp-validation-for="Difficulty" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsCompleted" /> @Html.DisplayNameFor(model => model.IsCompleted)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TodoApplication2/Views/Todos1/Delete.cshtml
@model TodoApplication2.Models.Todo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Todo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoneByDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoneByDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsCompleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsCompleted)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TodoApplication2/Views/Todos1/Details.cshtml
@model TodoApplication2.Models.Todo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Todo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoneByDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoneByDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsCompleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsCompleted)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TodoApplication2/Views/Todos1/Edit.cshtml
@model TodoApplication2.Models.Todo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Todo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoneByDate" class="control-label"></label>
                <input asp-for="DoneByDate" class="form-control" />
                <span asp-validation-for="DoneByDate" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <label asp-for="Difficulty" class="control-label"></label>
                <input asp-for="Difficulty" class="form-control" />
                <span asp-validation-for="Difficulty" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsCompleted" /> @Html.DisplayNameFor(model => model.IsCompleted)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TodoApplication2/Views/Todos1/Index.cshtml
@model TodoApplication2.Models.TodoTypeViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Todos1" asp-action="Index" method="get">
    <p>
        <select asp-for="TodoType" asp-items="Model.Types">
            <option value="">All</option>
        </select>

        Title: <input type="text" name="SearchString"/>
        <input type="submit" value="Filter"/>
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Todos[0].Title)
            </th>            <th>
                @Html.DisplayNameFor(model => model.Todos[0].Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Todos[0].DoneByDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Todos[0].IsCompleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Todos[0].Difficulty)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Todos) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>            
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoneByDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsCompleted)
            </td>            <td>
                @Html.DisplayFor(modelItem => item.Difficulty)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>